export const quizzesListArhitectura = [
  {
    id: 1,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q1.PNG',
    options: [
      {
        label: '11.2000; 3.42; 4.20;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '11.101; 3.5; 3.A;',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '2.1001; 3.52; 2D;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '11.10000; 3.20; 3.2A;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '11.10000; 2.42; 3.2;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 2,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q2.PNG',
    options: [
      {
        label: '216.5; 17.5; 27.52;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '218.75; 23.5; 27.625;',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '218.75; 22.5; 26.5;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '218.5; 23.5; 27.6;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '218.75; 23.55; 27.625;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 3,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q3.PNG',
    options: [
      {
        label: '+7.2;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '71',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '72',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '-71',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '-72',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 4,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q4.PNG',
    options: [
      {
        label: 'E3',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'E0',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'E1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'E2',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'EF',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 5,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q1.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a5a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a5b.jpg',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a5c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a5d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a5e.PNG',
      },
    ],
  },
  {
    id: 6,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q6.PNG',
    options: [
      {
        label: '44C58000;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'C1E40000;',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'C4B59000;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'C4C58000;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'CDFAA000;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 7,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q7.PNG',
    options: [
      {
        label: '3724;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3723;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3726;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3725;',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3727;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 8,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q8.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a8a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a8b.jpg',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a8c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a8d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a8e.jpg',
      },
    ],
  },
  {
    id: 9,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q9.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a9a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a9b.jpg',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a9c.jpg',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a9d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a9e.PNG',
      },
    ],
  },
  {
    id: 10,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q10.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a10a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a10b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a10c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a10d.jpg',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a10e.jpg',
      },
    ],
  },
  {
    id: 11,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q11.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a11a.PNG',
      },
      {
        label: 'a + bc',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a11c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a11d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a11e.PNG',
      },
    ],
  },
  {
    id: 12,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q12.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a12a.jpg',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a12b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a12c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a12d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/arhitectura/a12e.PNG',
      },
    ],
  },
  {
    id: 13,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q13.PNG',
    options: [
      {
        label: '1001;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1002;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1003;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1004;',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '1005;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 14,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q14.PNG',
    options: [
      {
        label: '1008;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1009;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '100A;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '100B;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '100C;',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 15,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q15.PNG',
    options: [
      {
        label: '600; 42;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '600; 2;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '452; 42;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '600; 24;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '452; 2;',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 16,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q16.PNG',
    options: [
      {
        label: '3251718;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3251711;',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3261711;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3261811;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3271711;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 17,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q1.PNG',
    options: [
      {
        label: '4000; 171;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3295; 170;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3294; 171;',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '4500; 200;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2951; 117;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 18,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q18.PNG',
    options: [
      {
        label: '37067620;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '32517180;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '32517160;',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '37007620;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '37062620;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 19,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q19.PNG',
    options: [
      {
        label: '144; 111; 31;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '150; 120; 131;',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '119; 053; 33;',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '150; 111; 131;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '155; 120; 131;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 20,
    category: 'Arhitectura calculatoarelor',
    question: '',
    questionImg: '../../../assets/quizzes-images/arhitectura/q20.PNG',
    options: [
      {
        label: 'R = B X (C + D|E + F | G);',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'R = B|(C + D|E + F | G);',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'R = B X (C + D|E - F X G);',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'R = B X (C + D|E + F|G);',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'R = B X (C + D X E + F X G);',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
];
