export const quizzesListOOP = [
  {
    id: 1,
    category: 'OOP',
    question: 'Un program orientat obiect reprezinta:',
    questionImg: '',
    options: [
      {
        label:
          'o colectie de obiecte care coopereaza prin intermediul mesajelor in vederea realizarii unui obiectiv comun',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'o varianta de program procedural',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'un program care poate fi considerat un obiect de catre alte programe',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'un program specific mediului de programare Windows',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'un program format din mai multe fisiere sursa si header',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 2,
    category: 'OOP',
    question: 'O clasa in modelul de programare orientat obiect reprezinta:',
    questionImg: '',
    options: [
      {
        label:
          'o colectie de obiecte cu aceleasi caracteristici si cu un comportament comun',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'o colectie de caracteristici',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'un obiect din program',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'o interfata',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'un grup de comportamente specific unui obiect',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 3,
    category: 'OOP',
    question: 'Obiectele apartinand unei aceleiasi clase se diferentiaza prin:',
    questionImg: '',
    options: [
      {
        label: 'starea lor',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'valorile datelor membru declarate in cadrul clasei',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'valorile caracteristicilor clasei',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'caracteristicile diferite specifice fiecarui obiect',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'comportamentul diferit specific fiecarui obiect',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 4,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q4.PNG',
    options: [
      {
        label: 'programul nu contine erori de sintaxa',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'exista erori de sintaxa in definitiile metodelor constructor',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'destructorul nu poate contine instructiuni de afisare',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'in cadrul programului principal sunt create doua instante ale clasei C',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'programul aseaza la consola numerele 3 si 4',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 5,
    category: 'OOP',
    question:
      'Care din urmatoarele afirmatii referitoare la mostenire sunt adevarate relativ la limbajul de programare C++:',
    questionImg: '',
    options: [
      {
        label:
          'Relatia de mostenire in care clasa de baza si clasa derivata au aceeasi interfata se numeste mostenire pura',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label:
          'Dintr-o clasa de baza se poate obtine prin intermediul mostenirii cel mult o clasa derivata',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'O clasa derivata are exact o clasa de baza',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'Obiectele apartinand unei clase derivate pot fi convertite la tipul unei clase de baza din care clasa derivata provine',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label:
          'Specicatorul protected este folosit pentru a arata ca elementele care il urmeaza pot fi accesate si din cadrul claselor derivate',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 6,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q6.PNG',
    options: [
      {
        label: '3 6 2 5',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3 6 16 1',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '6 6 10 1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 7 10 1',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'Eroare de compilare deoarce constructorul nu contine nici o intructiune',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 7,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q7.PNG',
    options: [
      {
        label: 'B1 B2 D DD DB2 DB1 DD DB2 DB1',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'B2 B1 D DD DB2 DB1 DD DB2 DB1',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D B1 B2 D DD DB2 DB1 DD DB2 DB1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D DD DB1 DB2 DD DB1 DB2',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'D DD',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 8,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q8.PNG',
    options: [
      {
        label: 'B1 B2 D(0) B1 B2 CD(1) DD DB2 DB1 DD DB2 DB1',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'B1 B2 D(0) DD DB2 DB1 DD DB2 DB1',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D(0) DD DB2 DB1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B2 B1 D(0) B1 B2 CD(1) DD DB2 DB1 DD DB2 DB1',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D(0) B2 B1 CD(1) DD DB2 DB1 DD DB2 DB1',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'rezultatul executiei nu poate fi determinat deoarce depinde de continul memoriei',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 9,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q9.PNG',
    options: [
      {
        label: 'B1 B2 D DD DB2 DB1',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'B1 B2 D DD DB2 DB1 DD DB2 DB1',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B2 B1 D DD DB2 DB1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B2 B1 D DD DB2 DB1 DD DB2 DB1',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D B1 B2 D DD DB2 DB1 DD DB2 DB1',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B1 B2 D B1 B2 D DD DB2 DB1',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 10,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q10.PNG',
    options: [
      {
        label: 'A()A(const A&)A(int,int)A(int,int)A(int,int)~A~A~A~A~A',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'A(const A&)A(const A&)A(int)A(int,int)A(int,int)~A~A~A~A~A',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A()A(const A&)A(int,int)A(int,int)A(int,int)~A~A~A~A',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A()A(const A&)A(int)A(int)A(int,int)~A~A~A~A~A',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A()A()A(int,int)A(int)A(int,int)~A~A~A~A~A',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'Eroare de compilare la declararea obiectului a2 deoarece nu e supraincarcat operatorul=.',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 11,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q11.PNG',
    options: [
      {
        label: 'B::f() D1::f() B::f() B::g() B::g() B::g()',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'D2::f() D1::f() B::f() B::g() B::g() B::g()',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B::f() D1::f() D::f() B::g() D1::g() D2::g()',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B::f() D1::f() B::f() B::g() D1::g() D2::g()',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B::f() B::f() D2::f() B::g() B::g() D2::g()',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 12,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q12.PNG',
    options: [
      {
        label: 'B::f() B::f() B::f()',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'D2::f() D1::f() B::f()',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B::f() D1::f() D2::f()',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B::f() D1::f() D2::f()',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 13,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q13.PNG',
    options: [
      {
        label: '2 5 2 1',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '2 0 0 0',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 5 2 1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 1 1 1',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 5 2 0',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 5 2',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Eroare de compilare',
        tag: 'G',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 14,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q14.PNG',
    options: [
      {
        label: '2 5 2 1',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '2 0 0 0',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 5 2 1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 1 1 1',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 5 2 0',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2 5 2',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Eroare de compilare',
        tag: 'G',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 15,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q15.PNG',
    options: [
      {
        label: '3 0 4 0 5 2 4 2',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3 0 4 0 5 0 4 2',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 4 5 2 4 2',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 3 4 4 5 2 4 2',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 0 4 0 5 2 5 2',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3 0 4 0 5 0 2 0',
        tag: 'F',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 16,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q16.PNG',
    options: [
      {
        label: '21',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '21.4',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '11',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'programul nu se compileaza',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 17,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q17.PNG',
    options: [
      {
        label: 'nimic (eroare de compilare)',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '0',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3.14',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'depinde de implementarea compilatorului',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 18,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q18.PNG',
    options: [
      {
        label: 'nimic (eroare de compilare)',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '1',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'depinde de implementarea compilatorului',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 19,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q19.PNG',
    options: [
      {
        label: '15',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '10',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '20',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'nimic (eroare de compilare)',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 20,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q20.PNG',
    options: [
      {
        label: 'Metoda afis() este incorect definita',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Constructorul este incorect definit',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Declaratie incorecta pentru obiectul A1',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Programul afiseaza valorile (10 20 0 0 )',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Programul afseaza valorile (0 0 10 20 )',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 21,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q21.PNG',
    options: [
      {
        label: '1 2 3 4',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1 3 4 5',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1 7 3 4',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '1 3 5 7',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '0 1 2 3',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 22,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q22.PNG',
    options: [
      {
        label: 'C c1(4,5)',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'C c2(0.0, 0,0)',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'C c3=c1',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'C c4(1)',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'C c5(c1)',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 23,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q23.PNG',
    options: [
      {
        label: 'Punct P1(10,20)',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Punct P2(P1(3))',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Punct P3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Punct P4=P1',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Punct P5(P1)',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 24,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q24.PNG',
    options: [
      {
        label: 'Obiectul p2 nu poate fi instantiat',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Asignarea p2 = ++ p1 este incorecta',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'In program se realizeaza supraancarcarea operatorului prefix de incrementare',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Programul va afisa valorile: 23',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Programul afiseaza valorile lui p1',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 25,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q25.PNG',
    options: [
      {
        label:
          'Utilizarea cuvantului predefinit "friend" nu este permisa in acest context',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Functia operatorului ++ nu este definita corect',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Programul va afisa valorile: 23 33',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Atribuirea a3=++a1+a2 este incorecta',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'programul va afisa valorile: 22 32',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 26,
    category: 'OOP',
    question:
      'Supraincarcarea unor operatori se poate realiza prin functii operator sau functii friend. Diferenta consta in:',
    questionImg: '',
    options: [
      {
        label: 'Precedenta operatorilor',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Asociativitatea operatorilor',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Obiectul returnat',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Lista de parametri',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Numarul parametrilor din lista functiei',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 27,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q27.PNG',
    options: [
      {
        label: 'Supraincarca operatorul()',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Supraincarca un operator unar',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label:
          'Este o metoda oarecare a clasei care nu produce supraincarcarea unor operatori',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Este un constructor',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Suprancarca operatorul[]',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 28,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q28.PNG',
    options: [
      {
        label: 'Toate',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(1), (2) si (5)',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(1), (3) si (4)',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(1), (2), (3), (4)',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(2), (4) si (5)',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 29,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q29.PNG',
    options: [
      {
        label: 'Toate',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Nici una',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'Numai (5)',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(2), (4) si (5)',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 30,
    category: 'OOP',
    question: '',
    questionImg: '../../../assets/quizzes-images/OOP/q30.PNG',
    options: [
      {
        label: '(1) si (4)',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(2), (3), (4)',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'Toate',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(6)',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
];
