export const quizzesListCorectitudine = [
  {
    id: 1,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q1.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1e.PNG',
      },
      {
        label: '',
        tag: 'F',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q1f.PNG',
      },
    ],
  },
  {
    id: 2,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q2.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q2a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q2b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q2c.PNG',
      },
    ],
  },
  {
    id: 3,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q3.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q3a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q3b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q3c.PNG',
      },
    ],
  },
  {
    id: 4,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q4.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q4a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q4b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q4c.PNG',
      },
    ],
  },
  {
    id: 5,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q5.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q5a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q5b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q5c.PNG',
      },
    ],
  },
  {
    id: 6,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q6.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q6a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q6b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q6c.PNG',
      },
    ],
  },
  {
    id: 7,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q7.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q7a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q7b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q7c.PNG',
      },
    ],
  },
  {
    id: 8,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q8.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q8a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q8b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q8c.PNG',
      },
    ],
  },
  {
    id: 9,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q9.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q9a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q9b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q9c.PNG',
      },
    ],
  },
  {
    id: 10,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q10.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q10a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q10b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q10c.PNG',
      },
    ],
  },
  {
    id: 11,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q11.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q11a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q11b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q11c.PNG',
      },
    ],
  },
  {
    id: 12,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q12.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q12a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q12b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q12c.PNG',
      },
    ],
  },
  {
    id: 13,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q13.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q13a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q13b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q13c.PNG',
      },
    ],
  },
  {
    id: 14,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q14.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q14a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q14b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q14c.PNG',
      },
    ],
  },
  {
    id: 15,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q15.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q15a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q15b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q15c.PNG',
      },
    ],
  },
  {
    id: 16,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q16.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q16a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q16b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q16c.PNG',
      },
    ],
  },
  {
    id: 17,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q17.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q17a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q17b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q17c.PNG',
      },
    ],
  },
  {
    id: 18,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q18.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q18a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q18b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q18c.PNG',
      },
    ],
  },
  {
    id: 19,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q19.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q19a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q19b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q19c.PNG',
      },
    ],
  },
  {
    id: 20,
    category: 'Corectitudine',
    question: '',
    questionImg: '../../../assets/quizzes-images/corectitudine/q20.PNG',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q20a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q20b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/corectitudine/q20c.PNG',
      },
    ],
  },
];
