export const quizzesListGrafuri = [
  {
    id: 1,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q1.PNG',
    options: [
      {
        label: 'A B C D E F',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A B D E C F',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'D B E A F C',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'D E B F C A',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'D E F B C A',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 2,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q2.PNG',
    options: [
      {
        label: 'J D P B H L R F N',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'J D B H F P L N R',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'N F R L H B P D J',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B D H F N L P R J',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B D F H L J N P R',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 3,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q3.PNG',
    options: [
      {
        label: 'B H F D L N P R J',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B D H F N L P R J',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'N F R L H B P D J',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'J D P B H L R F N',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B D F H J L N P R',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 4,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q4.PNG',
    options: [
      {
        label: 'A B C E F D G H I J',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'A B C D E F G H I J',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B E F C G H I J D A',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B A E C F G D H I J',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'B E F G H I J C D A',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 5,
    category: 'Grafuri',
    question:
      'Care este numarul maxim de componente conexe pe care le poate avea un graf neorientat cu 20 de noduri si 12 muchii?',
    questionImg: '',
    options: [
      {
        label: '6',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '12',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '10',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '15',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '18',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 6,
    category: 'Grafuri',
    question:
      'Cate grafuri neorientate, distincte, cu 4 varfuri se pot construi? Doua grafuri se considera distincte daca matricele lor de adiacenta sunt diferite.',
    questionImg: '',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q6a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q6b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q6c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q6d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q6e.PNG',
      },
    ],
  },
  {
    id: 7,
    category: 'Grafuri',
    question:
      'Intr-un graf neorientat cu 10 muchii, fiecare nod are gradul un num˘ar nenul. Doar trei dintre noduri au gradul un numar par, restul nodurilor avand gradele numere impare. Care este numarul maxim de noduri pe care poate sa le aiba graful?',
    questionImg: '',
    options: [
      {
        label: '14',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '10',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '17',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '16',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '19',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 8,
    category: 'Grafuri',
    question:
      'Determinati numarul de frunze ale arborelui cu radacina descris prin urmatorul vector tata: (6; 5; 5; 2; 0; 3; 3; 3; 8; 7; 7)?',
    questionImg: '',
    options: [
      {
        label: '1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '4',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '7',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 9,
    category: 'Grafuri',
    question:
      'Care dintre urmatoarele valori pot reprezenta gradele nodurilor unui graf neorientat cu 6 noduri?',
    questionImg: '',
    options: [
      {
        label: '(3; 2; 2; 2; 3; 3)',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(4; 2; 2; 2; 3; 2)',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(5; 2; 2; 2; 0; 3)',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(5; 2; 2; 2; 1; 2)',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '(5; 2; 3; 2; 1; 2)',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 10,
    category: 'Grafuri',
    question:
      'Se considera graful neorientat cu multimea varfurilor {1; 2; 3; 4; 5; 6} si multimea muchiilor {[1; 2]; [2; 3]; [3; 4]; [3; 5]; [4; 5]; [1; 3]; [2; 6]; [2; 4]; [4; 6] }. Care este numarul minim de muchii ce trebuie eliminate (care sunt aceste muchii) astfel incat graful partial obtinut sa nu mai fie conex?',
    questionImg: '',
    options: [
      {
        label: '1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '5',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'nici una',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 11,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q11.PNG',
    options: [
      {
        label: '1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '4',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '0',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 12,
    category: 'Grafuri',
    question:
      'Se considera graful neorientat cu 80 de noduri si 3160 de muchii. Care este numarul de muchii ce pot fi eliminate astfel incat graful partial obtinut sa devina arbore?',
    questionImg: '',
    options: [
      {
        label: '80',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3160',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3081',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '6320',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '2450',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 13,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q13.PNG',
    options: [
      {
        label: '1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '7',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '4',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 14,
    category: 'Grafuri',
    question:
      'Pentru care dintre urmatorii arbori cu radacina, fiecare avand 9 noduri, numerotate de la 1 la 9, memorati cu ajutorul vectorilor tata, nodul 3 are cei mai multi descendenti?',
    questionImg: '',
    options: [
      {
        label: '(2; 0; 2; 3; 2; 3; 4; 4; 3)',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(3; 3; 4; 0; 2; 3; 4; 4; 4)',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(4; 2; 4; 0; 3; 3; 3; 3; 3)',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '(0; 1; 1; 3; 4; 3; 4; 4; 3)',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(0; 1; 2; 3; 4; 5; 6; 7; 8)',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 15,
    category: 'Grafuri',
    question:
      'Care dintre urmatoarele proprietati este adevarata pentru un graf orientat cu n varfuri si n arce (n > 3) si care prezinta un circuit de lungime n:',
    questionImg: '',
    options: [
      {
        label: 'exista un varf cu gradul intern n - 1.',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'pentru orice varf, gradul intern si gradul extern sunt egale.',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'graful nu are drumuri de lungime strict mai mare decat 2.',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'gradul intern al oricarui varf este egal cu 2.',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'daca notam graful cu G = (V,E), |V| = n, atunci |E| = n - 1.',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 16,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q16.PNG',
    options: [
      {
        label: '5; 2; 1; 3; 4; 7; 6; 8',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5; 2; 1; 3; 5; 7; 6; 8',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5; 7; 6; 4; 8; 2; 1; 3',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5; 2; 7; 1; 6; 3; 4; 8',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '5; 7; 2; 6; 1; 8; 4; 3',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 17,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q17.PNG',
    options: [
      {
        label: '3; 5; 7; 6; 4; 8; 2; 1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3; 5; 2; 7; 1; 6; 4; 8',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3; 5; 2; 1; 4; 7; 6; 8',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '3; 5; 2; 1; 4; 6; 8; 7',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3; 5; 2; 7; 1; 4; 6; 8',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 18,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q18.PNG',
    options: [
      {
        label: '5; 6',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '8; 5',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '7; 6',
        tag: 'C',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '7; 7',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '6; 7',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 19,
    category: 'Grafuri',
    question:
      'Daca pentru un arbore binar avem un numar de N muchii, sa se determine numarul de muchii critice ale arborelui?',
    questionImg: '',
    options: [
      {
        label: 'N-1',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'N+2',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'N/2',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '(N+1)/2',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'N',
        tag: 'E',
        isCorrect: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 20,
    category: 'Grafuri',
    question:
      'Daca avem un arbore binar plin cu 9 nivele, sa se determine numarul de varfuri ce se afla pe nivelul cu numarul 5?',
    questionImg: '',
    options: [
      {
        label: '',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q20a.PNG',
      },
      {
        label: '',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q20b.PNG',
      },
      {
        label: '',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q20c.PNG',
      },
      {
        label: '',
        tag: 'D',
        isCorrect: true,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q20d.PNG',
      },
      {
        label: '',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
        ansImg: '../../../assets/quizzes-images/grafuri/q20e.PNG',
      },
    ],
  },
  {
    id: 21,
    category: 'Grafuri',
    question:
      'Avand un arbore binar reprezentat prin urmatoarea expresie cu paranteze: 1(2(3(0; 4(0; 0)); 5(6(0; 0); 7(0; 0))),8(0; 9(0; 0))). Sa se determine numarul de frunze ale grafului.',
    questionImg: '',
    options: [
      {
        label: '4',
        tag: 'A',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: '3',
        tag: 'B',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '5',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '9',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: '6',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 22,
    category: 'Grafuri',
    question: '',
    questionImg: '../../../assets/quizzes-images/grafuri/q22.PNG',
    options: [
      {
        label: 'A;C;B;D;E;',
        tag: 'A',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A;B;D;E;C;',
        tag: 'B',
        isCorrect: true,
        isSelected: false,
      },
      {
        label: 'A;D;E;C;B;',
        tag: 'C',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A;B;D;C;E;',
        tag: 'D',
        isCorrect: false,
        isSelected: false,
      },
      {
        label: 'A;B;E;B;D;',
        tag: 'E',
        isCorrect: false,
        isSelected: false,
      },
    ],
  },
];
